import React from 'react';

import type {Metadata} from 'next';
import {Open_Sans} from 'next/font/google';

import '@/core/styles/globals.css';

import {Providers} from '@/core/providers/Providers';

const openSans = Open_Sans({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Asana clone',
    description: 'Generated by create-next-app@latest.',
};

export default async function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={openSans.className}>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
