import React from 'react';
import type {Metadata} from 'next';

import '@/core/styles/globals.css';

import {Open_Sans} from 'next/font/google';
import {getServerSession} from 'next-auth/next';

import {Providers} from '@/core/providers/Providers';

import {authOptions} from '@/shared/configs/authConfig';

import {Header} from '@/widgets/header';

const openSans = Open_Sans({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Asana clone',
    description: 'Generated by create-next-app@latest.',
};

const RootLayout = async ({
    children
}: Readonly<{
    children: React.ReactNode
}>) => {
    const session = await getServerSession(authOptions);

    return (
        <html lang="en">
            <body className={openSans.className}>
                <Providers session={session}>
                    <Header />
                    {children}
                </Providers>
            </body>
        </html>
    );
};

export default RootLayout;
