import type {Metadata} from 'next';
import {Open_Sans} from 'next/font/google';

import '@/core/styles/globals.css';

import {ThemeProvider} from '@/core/providers/ThemeProvider';

const openSans = Open_Sans({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Asana clone',
    description: 'Generated by create-next-app@latest.',
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={openSans.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    Hello world!
                </ThemeProvider>
            </body>
        </html>
    );
}
